### ISSUE TITLE
`brew upgrade` is broken

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/homebrew-dnx#20]
`brew upgrade dnvm` should actually update DNVM on Mac. The current recipe does not actually update with dnvm changes. Add a version number to the recipe so brew will notice changes.

Without this, it appears to users the DNVM is updated, even when its not. This leads to other issues, such as https://github.com/aspnet/dnx/issues/2126.

Even when https://github.com/aspnet/dnvm/issues/246 is resolved, `brew upgrade` is more familiar upgrade path for users.

** Workaround **
```
brew remove dnvm
brew update
brew install dnvm
```

**Comment by muratg** [comment]
@davidfowl Should we just remove homebrew installer and use Curl or something to do the initial installation?

**Comment by natemcmaster** [comment]
Brew is very popular. I think it's worth keeping. Just my 2 cents.

**Comment by muratg** [comment]
I love brew myself, it's great for a lot of things. But installing a version manager _with a package manager_ is a little weird. 

For example, there's no official brew formula for nvm ([see the discussion]( https://github.com/creationix/nvm/issues/469)) and on their [Readme](https://github.com/creationix/nvm) they recommend curl or wget to install it.

**Comment by natemcmaster** [comment]
Yeah, it is strange. Also [RVM](https://rvm.io/) doesn't use brew. I believe we used setup this repo because it makes installing mono easier.

**Comment by anurse** [comment]
Yeah, it's mostly about Mono. We did it so that the `kvm` (at the time) recipe could depend on the right Mono package. As Mono is stabilizing a little bit (and we're getting CoreCLR on Mac up and running) it's probably time to look at moving away from brew. I'm with @muratg, I love brew but it isn't quite right for what we're trying to do here. We could return to brew when we build installers for Mac/Linux that are focused more on production systems (i.e. where dnvm is less interesting). I know @glennc has played with building a Mac OS X `pkg` installer, we could have a similar brew installer for the `dnx` itself (rather than for `dnvm`)

**Comment by muratg** [comment]
@davidfowl time to pull the plug for brew formula for dnvm? :)

**Comment by anurse** [comment]
My suggestion would be to ensure the curl script works on Mac (I think I tried it once and it worked fine) and change the Home repo instructions to that. Then, possibly, deprecate the Brew formula by printing a warning message or something (not sure if brew has a deprecation mechanism)

**Comment by natemcmaster** [comment]
This worked just fine for me too.

`curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | bash`

I suggest adding a line to `dnvminstall.sh` to source dnvm.sh right away to make it `dnvm` instantly accessible.

**Comment by natemcmaster** [comment]
@anurse AFAIK there is no deprecation flag for brew. Probably better to remove the formula altogether.

**Comment by anurse** [comment]
@natemcmaster Unfortunately, because the `dnvminstall.sh` script is run in a sub-process, having it call `source dnvm.sh` would not actually work. `dnvm` would be loaded into the sub-process which would immediately exit. We can probably put it in the command line though, something like `curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | bash && source ~/.dnx/bin/dnvm.sh`

As for deprecating/removing the brew formula, I thought that might be the case. I agree that removing it will probably be best.

**Comment by anurse** [comment]
What's the work item here @muratg ? To me it sounds like: 

1. Remove the DNVM formula from Homebrew, or replace it with an error or something
2. Update docs.asp.net and Home to use the `curl` command.

**Comment by muratg** [comment]
@anurse yup, and test the curl command to make sure. When we update the documentation, we should also recommend a Mono version to install (and possibly a link)

**Comment by anurse** [comment]
Ok, sounds good!

**Comment by anurse** [comment]
Confirmed that the `curl` command works fine on Mac. I'll work on some documentation updates for the Mac process.

**Comment by muratg** [comment]
Looks like we're placing dnvm in ~/.dnx/dnvm these days. Make sure to update the command line to reflect that :)

**Comment by anurse** [comment]
Yep.
